#!/bin/sh
# Usage:
# ./scripts/cov [reporter]

cd $(dirname $0)/..

COV=./node_modules/.bin/coffeeCoverage
MOCHA=./node_modules/.bin/mocha

REPORTER=$1
echo "Using Mocha reporter: $REPORTER" 1>&2
$COV --exclude node_modules,.git,test --path relative . ./src-cov 1>&2
cp -r ./test ./src-cov/test
cp ./package.json ./src-cov
find ./src-cov/test/unit | grep "\-test" | xargs $MOCHA  --reporter $REPORTER --compilers 'coffee:coffee-script'

rm -rf ./src-cov
